CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(500) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`category` varchar(100) NOT NULL DEFAULT 'Nuts',
	`price` int NOT NULL,
	`mrp` int NOT NULL,
	`discount` int NOT NULL DEFAULT 0,
	`weight` varchar(100) DEFAULT '',
	`description` longtext,
	`ingredients` text,
	`nutritionalInfo` text,
	`shelfLife` varchar(100),
	`storageInfo` text,
	`image` text NOT NULL,
	`images` json,
	`isBestseller` boolean NOT NULL DEFAULT false,
	`isTrending` boolean NOT NULL DEFAULT false,
	`isNew` boolean NOT NULL DEFAULT false,
	`available` boolean NOT NULL DEFAULT true,
	`rating` int NOT NULL DEFAULT 45,
	`reviewCount` int NOT NULL DEFAULT 0,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`),
	CONSTRAINT `products_handle_unique` UNIQUE(`handle`)
);
